// <auto-generated />
namespace Progamacion3F.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ClientesClassv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientesClassv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004070650194_ClientesClass-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
